### ISSUE TITLE
update dependencies and freeze them

### ISSUE THREAD

**Issue by aryam7** [aryam7/varCA#10]
update them to their newest versions and then freeze them in the envs file
(specifically, consider updating `mlr`)

this will decrease the chance of bugs arising in the future from new versions of the dependencies

**Comment by aryam7** [comment]
apparently `data.table` and `mlr` conflict in `envs/classify.yml`
you should fix that

**Comment by aryam7** [comment]
A note on mlr3:
Updating from mlr2 to mlr3 would require rewriting several of our scripts, since the syntax has changed dramatically in mlr3
and yet doing so wouldn't really seem to offer much of a benefit to us, especially since the move from mlr2 to mlr3 was primarily to change the syntax, as far as I can tell (source: https://mlr-org.com/docs/mlr3-0-1-0/)

**Comment by gmcvicker** [comment]
If using mlr2 gives warnings to upgrade to mlr3 when the software is run, then i think we should probably go ahead and update the code. If switching is a lot of work, could we instead suppress the warning messages?
