### ISSUE TITLE
example data

### ISSUE THREAD

**Issue by aryam7** [aryam7/varCA#9]
provide example data for running the pipeline from start to finish

**Comment by aryam7** [comment]
and set up the config files so that the pipeline can easily work that data out of the box

remove mentions of any of my own paths from the config files

**Comment by aryam7** [comment]
maybe we could try a smaller dataset so things run faster? maybe just a single chromosome?

**Comment by gmcvicker** [comment]
I think it's a good idea to have a smaller dataset to make the example run faster.
